name: HPDCS
markdown: kramdown
highlighter: pygments
exclude: [README.md, pubs.bib, LICENSE, upload.sh]

url: "https://www.diag.uniroma1.it/~pellegrini"

# Blog posts map to courses
permalink: /didattica/:year/:title.html

sass:
  style: compressed

# For publications
plugins: ['jekyll/scholar']
scholar:
  style: apa
  source: ./
  bibliography: pubs.bib
  sort_by: year,month
  order: descending
  group_by: year
  group_order: descending
  repository: publications
  bibliography_template: bibliography
  bibliography_list_tag: ul
